# Generated by Django 5.0.6 on 2024-06-03 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_children_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='dateOfAdmission',
            field=models.DateField(),
        ),
    ]
